### ISSUE TITLE
'Unprocessable Entity' 422 error when adding value to a condition with no key

### ISSUE THREAD

**Issue by pmallol** [instedd/aida-ui#108]
Version ui: 0.4.0-dev-0372001 (build 388) - engine: 0.4.0-dev-0a7f916 (build 155)

1. Navigate to Translations
2. Click on Variables
3. Add a Variable and fill out its input fields
4. Add a condition and only fill out a value field

Obtained: a 422 error in the console

![screen shot 2018-01-16 at 3 38 53 pm](https://user-images.githubusercontent.com/9214460/35005799-70164842-fad3-11e7-8775-ee5e688c711d.png)

**Comment by ggiraldez** [comment]
This overzealous validation is the cause:
https://github.com/instedd/aida-ui/blob/master/app/models/variable_assignment.rb#L64

OTOH, if we remove the restriction, attempting to publish the bot with an empty condition triggers an `Invalid expression: ''` from the backend, presumably from the empty `relevant` condition on the variable.

I see two options:

1. remove the constraint and default the `relevant` condition to `true` if empty
2. keep the constraint and indicate an error in the UI

Option 1 is generally better from a UX/UI point of view. Option 2 would disallow saving the variable configuration until the error is fixed.

**Comment by bcardiff** [comment]
Let's change the validation to detect nil or not nil (instead of blank/present). That will allow empty strings.

I would let the backend fail for know until there is a better error handling. Making empty strings == true on manifest generation seems weird to me.
