### ISSUE TITLE
Preview prints each message around 20 times

### ISSUE THREAD

**Issue by lenahohfeld** [instedd/aida-ui#109]
I found the preview to be unstable. It stops working in between, now it prints each message around 20 times.

**Comment by bcardiff** [comment]
Hi @lenahohfeld, Thanks for reporting we will stress a bit more the preview and see what can be done.  May I ask you to describe how you are using the preview? 

Does it happens almost right away or after you've left the page open for a while or computer suspended?

Do you stay always in the behavior section for this to happen or you navigate back and forth through the pages of the bot?

Last but not least, if you could include the version that can be found at the bottom of the page it would help us identify the issue and test more accordingly.

**Comment by lenahohfeld** [comment]
Sorry Brian for the late response.
Actually I do not remember the exact situation when it appeared, and it disappeared by now. I will track and report the situation better and in more detail next time.

Best,
Lena
