### ISSUE TITLE
Tables are not being shared

### ISSUE THREAD

**Issue by nditada** [instedd/aida-ui#134]
Even when content and variable access has been granted to a collaborator, tables are not shown for them. I would treat variables and tables the same, and rename the 'variables' permission to 'variables and tables'.

**Comment by vtiffenberg** [comment]
@nekron are we going with the suggestion here? Adding tables to the existing variables permission?

**Comment by nekron** [comment]
Yes 👍

**Comment by mmuller** [comment]
Working properly in version 0d0fdaf

**Comment by mmuller** [comment]
Working properly in version 0d0fdaf

**Comment by mmuller** [comment]
Version 0d0fdaf
Working properly when the collaborator has access to  `Publish`. Collaborators can view and modify tables.
It doesn't work when the collaborator has access on  `Variables and tables`. Collaborators cannot view and modify tables.
