### ISSUE TITLE
Display validation errors in decision trees

### ISSUE THREAD

**Issue by nekron** [instedd/aida-ui#171]
Related to #147

Some messages that the UI should easily understand:
```
{
  "errors": [
    {
      "message": "required",
      "path": ["skills/0", "keywords/en"]
    },
    {
      "message": "required",
      "path": ["skills/0", "tree/node-id-1", "message"]
    },
    {
      "message": "required",
      "path": ["skills/0", "tree/node-id-1", "options/0"]
    },
    {
      "message": "children issues",
      "path": ["skills/0", "tree/node-id-1", "options/0"]
    },
    {
      "messsage": "required",
      "path": ["skills/0", "tree/node-id-1", "answer"]
    }
  ]
}
```

Required messages should turn the message box red. Required options should add a red indicator to the Add Option button. Children issues should add a red indicator to the option, so the user clicks it to find out what the error is. The Children issues should apply to every ancestor of an error.

**Comment by mmuller** [comment]
Working properly in version e5a4144
