### ISSUE TITLE
Add message counter to the Messages tab

### ISSUE THREAD

**Issue by nekron** [instedd/aida-ui#177]
The top navigation label should indicate the number of pending messages. See the `(24)` in the original design proposal.

https://projects.invisionapp.com/d/main/default/#/console/12115078/305180030/preview

**Comment by nekron** [comment]
Fixed with 9ced92e20815f2cdacb87f6a31a8b9f7b66dc447

**Comment by mmuller** [comment]
Working properly in version b8baf1e
