### ISSUE TITLE
[Decision tree] Option with validation error is not aligned.

### ISSUE THREAD

**Issue by mmuller** [instedd/aida-ui#198]
Version e5a4144

![image](https://user-images.githubusercontent.com/518152/43781295-f30223a8-9a32-11e8-9d9f-2f2b4646decf.png)

**Comment by nekron** [comment]
The "children" message should be displayed as a red dot to indicate that there is an error in one of the child nodes of the tree

**Comment by nekron** [comment]
<img width="543" alt="screen shot 2018-08-07 at 16 13 46" src="https://user-images.githubusercontent.com/957103/43797179-f3af0f80-9a5c-11e8-9688-0e1c307c69fc.png">

It's a compromise solution, the whole tree will be redesigned in 1.2 (instedd/aida#204)

**Comment by mmuller** [comment]
Working properly in version 17444c4
