### ISSUE TITLE
Style operator button in human override

### ISSUE THREAD

**Issue by aeatencio** [instedd/aida-ui#204]
For instedd/aida#221

Expected: 
![image](https://user-images.githubusercontent.com/39921597/43995420-db22c612-9d83-11e8-9d8b-c21ef96ef775.png)
Current:
![image](https://user-images.githubusercontent.com/39921597/43995433-f708f8b0-9d83-11e8-9f77-090a4272857b.png)

**Comment by mmuller** [comment]
Working properly in version 204eed2
