### ISSUE TITLE
What is the correct authorization to join a channel/bot via JS client?

### ISSUE THREAD

**Issue by zontarian** [instedd/aida-ui#239]
Hi,
I'm trying to connect to a Bot I've created, using a JS client (so, websockets). This is my first go at it.
I'm using as a starting point
https://hexdocs.pm/phoenix/js/#phoenix
https://github.com/instedd/aida-ui/blob/master/app/javascript/components/ChatClient.jsx

So far I've managed to open the Phoenix socket and connect to it, but when I try to join the channel Iike this
```    
let socket = new Socket('wss://aida.xxxxxx.org/socket');
socket.connect();
let channel = socket.channel('bot:'+botId, {'access_token': accessToken}); //<-- error here
```
I get

`{reason: "unauthorized"}`

`botId` is a number, the one I see in this URL `https://aida.xxxxxxxxx.org/b/10/channel` (10). While `accessToken` is the token I've written in the `Channel` tab of my Bot configuration, under the heading 
![screen shot 2018-09-19 at 15 46 29](https://user-images.githubusercontent.com/2872433/45757255-35f62080-bc23-11e8-9b1f-a3068e4a049e.png)

So, what is the correct authorization? 
Thanks
Walter

**Comment by zontarian** [comment]
Well..it seems my parameters were wrong.
By debugging the chat in the "Behaviour" tab, I discovered
* a `uuid` for the bot. It's something like `ae9c0c65-xxx-xxxx-xxxx-xxxxxxxxxxx` (obfuscated..) so it seems it's not `10`
* an access token which is different again, in the same UUID hex form of 16bytes in hex.

Now the question is, how to infer these values from the info on the web site? :)

**Comment by nekron** [comment]
Closed in favor of https://github.com/instedd/aida/issues/276
