### ISSUE TITLE
Creating a web channel in a newly created bot will provide an invalid link

### ISSUE THREAD

**Issue by nekron** [instedd/aida-ui#247]
Until the bot is deployed, it has no uuid, so the web channel link will contain null instead.

<img width="1643" alt="screen shot 2018-09-28 at 12 58 27" src="https://user-images.githubusercontent.com/957103/46219665-4b073980-c31e-11e8-9ba8-4a778c338d38.png">

We can display some advice to encourage the user to publish the bot, and hide that link until then.

@jkicillof any quick thoughts about it?

**Comment by mmuller** [comment]
Working properly in version e9da607
