### ISSUE TITLE
Publish bot from bot menu

### ISSUE THREAD

**Issue by aeatencio** [instedd/aida-ui#253]
Version bda8eaf 

As a new option of the hamburger menu

**Comment by mmuller** [comment]
Expected: 

<img width="703" alt="screen shot 2018-10-04 at 10 45 14" src="https://user-images.githubusercontent.com/518152/46478135-ade74d80-c7c2-11e8-9b04-819d3c5d6ab4.png">

**Comment by mmuller** [comment]
Working properly in version e9da607
