### ISSUE TITLE
Parse choice filter for cascading select and send in manifest

### ISSUE THREAD

**Issue by bcardiff** [instedd/aida-ui#89]
Related: https://github.com/instedd/aida/issues/52
https://instedd.storiesonboard.com/m/chatbots/!card/nfq9kW1WrB14bzniciCoiQ

http://xlsform.org/#cascade

**Comment by waj** [comment]
Also, custom attributes for each choice must be parsed and specified in the manifest:
https://github.com/instedd/aida/blob/feature/52-cascading-selects/test/fixtures/valid_manifest.json#L216-L218

**Comment by bcardiff** [comment]
xlsform is a bit ambiguous regarding uniqueness of values. The spec for choices says values should be unique, but the samples does not validate that.

kobotoolbox allows non unique values.

So if we relax uniqueness of value, for i18n we either need to translate all possible combination `(value, attributes)` or assume that all occurrences of `value` will be translated equally.

This happens for example in states>counties>cities, there might be more than one counties named the same. It's more common to assume the values won't be unique for simplicity of the user.

Let's use `value` as the key for translation and allow non unique `(value, attributes)` in the parsing of the xls form.
