### ISSUE TITLE
Some Text fields don't have any indicator to edit its content

### ISSUE THREAD

**Issue by pmallol** [instedd/aida-ui#99]
Version 0.4
Text fields inside Tables
<img width="1317" alt="screen shot 2018-01-11 at 2 41 49 pm" src="https://user-images.githubusercontent.com/9214460/34838647-b0f5c030-f6dd-11e7-989a-cc2ede0bc231.png">
and 

<img width="360" alt="screen shot 2018-01-11 at 2 43 13 pm" src="https://user-images.githubusercontent.com/9214460/34838718-eeb61096-f6dd-11e7-975f-dc4ec22d0a7b.png">

Bot's name text field
<img width="310" alt="screen shot 2018-01-11 at 2 43 26 pm" src="https://user-images.githubusercontent.com/9214460/34838729-f50d0562-f6dd-11e7-814a-e3cec14dd374.png">

**Comment by bcardiff** [comment]
Also since the default language is not editable in content translation, it would be good to have some difference there
